version: "3.9"
services:
  prisma-postgres-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: prisma-postgres-ts-dev-api
    ports:
      - "3000:3456"
    restart: always
